//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatternApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkMainArticle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkMainArticle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignPatternApp.Resources.LinkMainArticle", typeof(LinkMainArticle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/design-patterns/abstract-factory.
        /// </summary>
        internal static string DPAbstractFactory {
            get {
                return ResourceManager.GetString("DPAbstractFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/design-patterns/adapter.
        /// </summary>
        internal static string DPAdapter {
            get {
                return ResourceManager.GetString("DPAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/design-patterns/builder.
        /// </summary>
        internal static string DPBuilder {
            get {
                return ResourceManager.GetString("DPBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/fr/design-patterns/facade.
        /// </summary>
        internal static string DPFacade {
            get {
                return ResourceManager.GetString("DPFacade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/design-patterns/factory-method.
        /// </summary>
        internal static string DPFactoryMethod {
            get {
                return ResourceManager.GetString("DPFactoryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/fr/design-patterns/proxy.
        /// </summary>
        internal static string DPProxy {
            get {
                return ResourceManager.GetString("DPProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://refactoring.guru/design-patterns/singleton.
        /// </summary>
        internal static string DPSingleton {
            get {
                return ResourceManager.GetString("DPSingleton", resourceCulture);
            }
        }
    }
}
